### ISSUE TITLE
make modo add remote-compatible

### ISSUE THREAD

**Issue by cmdoret** [sdsc-ordes/modo-api#22]
Modo add creates a folder locally. To support remote write operations we can directly "mount" the s3 folder

**Requirements:**
* [x] rely on zarr's built-in s3 support to update metadata transparently
* [x] use s3fs (?) to manually upload / remove / delete files on s3

> note for now we ignore access control and use anon buckets

**Comment by almutlue** [comment]
## Re metadata update:
- `add` works without adaptation using the current implementation, if an `s3_endpoint` is set.
- `zarr.consolidate_metadata(zarr.Group)` does not work properly for remote endpoints (looks related to: https://github.com/zarr-developers/zarr-python/issues/1121)
- `remove` does not work, even if the `s3_endpoint` is set (why)

### TODO
- [ ] find a fix for `consolidate_metadata` with remote objects
- [ ] fix remove for remote storage
- [ ] adapt cli to work with remote objects
